name: aur-publish

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish AUR package
        uses: anas-elgarhy/aur-release-action@v4.1
        continue-on-error: true
        with:
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          update_pkgbuild: true
          try_build_and_install: true
          git_username: Asempere
          git_email: asempere158@gmail.com
